image:
  file: .gitpod.dockerfile

tasks:
  - name: initialize
    before: |
      echo "🚀 before"
      # ------------------------------------
      # wasmer
      # ------------------------------------
      source /home/gitpod/.wasmer/wasmer.sh
      wasmer --version
      # ------------------------------------
      # wasmtime
      # ------------------------------------
      wasmtime --version
      # ------------------------------------
      # wasmedge dependencies
      # ------------------------------------
      source /home/gitpod/.wasmedge/env 
      wasmedge --version

      # ------------------------------------
      # Swift Wasm toolchain
      # ------------------------------------
      sudo echo "" >> $HOME/.bashrc
      sudo echo 'export SWIFT_WASM_HOME="swift-wasm-5.6.0-RELEASE"' >> $HOME/.bashrc
      sudo echo "" >> $HOME/.bashrc
      sudo echo 'export PATH=$HOME/${SWIFT_WASM_HOME}/usr/bin:"${PATH}"' >> $HOME/.bashrc
      source $HOME/.bashrc


    init: |
      echo "🚀 init"


vscode:
  extensions:
    - pkief.material-icon-theme
    - bungcip.better-toml
    - aaron-bond.better-comments




