image:
  file: .gitpod.dockerfile

tasks:
  - name: initialize
    before: |
      echo "🚀 before"
      # ------------------------------------
      # wasmer
      # ------------------------------------
      source /home/gitpod/.wasmer/wasmer.sh
      wasmer --version
      # ------------------------------------
      # wasmtime
      # ------------------------------------
      wasmtime --version
      # ------------------------------------
      # wasmedge dependencies
      # ------------------------------------
      source /home/gitpod/.wasmedge/env 
      wasmedge --version


    init: |
      echo "🚀 init"


vscode:
  extensions:
    - pkief.material-icon-theme
    - bungcip.better-toml
    - aaron-bond.better-comments




